### ISSUE TITLE
no PySympleGUI

### ISSUE THREAD

**Issue by TeamSoldierNub2** [Bloxxel64/SM64LinuxLauncher-Legacy#1]
Doing `python3 launcher.py` in the src dir does this

`Traceback (most recent call last):
  File "builder.py", line 4, in <module>
    import PySimpleGUI as sg
ModuleNotFoundError: No module named 'PySimpleGUI'`

What's going on? am I missing a module or is there an issue?

**Comment by TeamSoldierNub2** [comment]
nevermind, issue of own fault

**Comment by Packers4Evar12** [comment]
I am also getting the "No module named 'PySimpleGUI'" error. Posting the solution instead of "nvm, figured it out" would have been awesome.

**Comment by hxdeci** [comment]
> I am also getting the "No module named 'PySimpleGUI'" error. Posting the solution instead of "nvm, figured it out" would have been awesome.

install the package `PySimpleGUI` via Pip: `python3 -m pip install PySimpleGUI`
