### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by PaperVb64** [Bloxxel64/SM64LinuxLauncher-Legacy#10]
soo, i clicked build and it gives me this whole shpiel:
`Traceback (most recent call last):
  File "/home/usr/sm64linlaunch/src/./launcher.py", line 74, in <module>
    main()
  File "/home/usr/sm64linlaunch/src/./launcher.py", line 51, in main
    values['buildlist'][0] # load the builds
IndexError: list index out of range`
what's going on???

**Comment by ezntek** [comment]
did you build anything prior to this?

**Comment by PaperVb64** [comment]
In the app? No. Outside of the app? just LinuxLauncher.

**Comment by ezntek** [comment]
can you tell me, in detail, exactly what you did leading up to this event? How do you reproduce this issue, and what was the state of the application before you got the issue?

**Comment by PaperVb64** [comment]
Before i tried building sm64 with it, for some reason the window was disfigured.

**Comment by ezntek** [comment]
Can you show me what the disfiguration looked like, and why it is an issue (or why it is related to the application crashing)?

**Comment by PaperVb64** [comment]
i can't. Never grabbed a screenshot. I think i remember it just being one of the text windows displaying?

**Comment by ezntek** [comment]
can you reproduce this issue with a clean install?

**Comment by ezntek** [comment]
if there are no further inquiries, please close this issue.

**Comment by nt5point1** [comment]
can confirm that this also happens on linux mint 21.2. when i click the build button, the launcher just crashes with the same error that PaperVb64 sent.

**Comment by ezntek** [comment]
I must make a revelation: this project is pretty much dead. No commits since early this year, no new features and no bugfixes. I can submit patches for you all, but they must go through the maintainer @Bloxxel64 first. I'll notify him of these issues to take further action as soon as I can.

**Comment by Bloxxel64** [comment]
ough, im not good at maintaining stuff

im sorry for all the issues yall have gotten, i will (hopefully soon) see about getting this up and maintained again. thanks soooo much @ezntek for all the help you've been. :3

**Comment by Bloxxel64** [comment]
bit of an update, i found the issue, partially, i should have a fix out very soon.

**Comment by Bloxxel64** [comment]
@PaperVb64 @mrfas12 the newest commit should have a  working fix :3

**Comment by Bloxxel64** [comment]
i put the files in the root not in /src, oops
