### ISSUE TITLE
No builds

### ISSUE THREAD

**Issue by Malo1301** [Bloxxel64/SM64LinuxLauncher-Legacy#12]
The title is pretty self-explanatory, the build list contains no builds.
[image](https://github.com/Bloxxel64/SM64LinuxLauncher/assets/153450736/b0da5fd6-6323-46e2-9bcc-8cd555ad1f51)

Clicking the "Build" button results in this:
`Traceback (most recent call last):
  File "/home/malo/SM64LinuxLauncher/src/launcher.py", line 73, in <module>
    main()
  File "/home/malo/SM64LinuxLauncher/src/launcher.py", line 51, in main
    values['buildlist'][0] # load the builds
    ~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/malo/SM64LinuxLauncher/src/launcher.py", line 75, in <module>
    import builder
  File "/home/malo/SM64LinuxLauncher/src/builder.py", line 28
    'sm64coopdx-dev,
    ^
SyntaxError: unterminated string literal (detected at line 28)
malo@legion5malo:~/SM64LinuxLauncher/src$ python3 /home/malo/SM64LinuxLauncher/src/launcher.py
Traceback (most recent call last):
  File "/home/malo/SM64LinuxLauncher/src/launcher.py", line 73, in <module>
    main()
  File "/home/malo/SM64LinuxLauncher/src/launcher.py", line 51, in main
    values['buildlist'][0] # load the builds
    ~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/malo/SM64LinuxLauncher/src/launcher.py", line 75, in <module>
    import builder
  File "/home/malo/SM64LinuxLauncher/src/builder.py", line 28
    'sm64coopdx-dev,
    ^
SyntaxError: unterminated string literal (detected at line 28)`
This is probably because my builds.txt is empty, so no builds :(

**Comment by ezntek** [comment]
I'm sorry, but this repo is extremely poorly maintained, I'm trying to help @Bloxxel64 as much as possible, but I'm not that familiar with the codebase and the toolkit, and I only have so much time to fix bugs.

it could be linked to commit 8d99251 though.

**Comment by ezntek** [comment]
If you really want to play, you may as well just learn how to compile it (it isn't that hard). It usually only involves cloning the repository, copying the base ROM and running `make`; assuming that you have the dependencies.

**Comment by Bloxxel64** [comment]
Honestly this old codebase is getting to a point where I can't keep working on it for shite. Starting hopefully soon I'm going to rewrite this in either Python or C++ with qt. In the meantime I'll see what I can do to cook up a somewhat stable final version...

**Comment by ezntek** [comment]
Actually, my summer break is coming up, should I help co-author?

I don't think C++ is a good idea in general, its too messy of a language especially after scaling. Maybe try something like Go? If you _really_ want to use C++ it's also fine, just do not mess with Python and Qt (I tried to make SM64LinuxLauncher around a year ago, it wasnt cool).

**Comment by ezntek** [comment]
As for stability, just forget it, just direct people to ezntek/smbuilder for now (it is CLI only and extremely hacky but it does make completely equal reproducible builds).

**Comment by ezntek** [comment]
@Bloxxel64 can I shoot you an email for discussion purposes?

**Comment by Bloxxel64** [comment]
> @Bloxxel64 can I shoot you an email for discussion purposes?

uuuuh, i dont feel like giving out my email, sorry. would there be another way we can discuss? discord perhaps.

**Comment by ezntek** [comment]
that'll work.

**Comment by ezntek** [comment]
The whole reason as to why i asked for the email was i thought it was a bad idea to share peoples' discord usernames in a public issues forum.

**Comment by Bloxxel64** [comment]
> The whole reason as to why i asked for the email was i thought it was a bad idea to share peoples' discord usernames in a public issues forum.

nah it's fine, im around discord and the internet enough to not be worried about it anyway, my username on disc in 'bloxxel64colonthree'

**Comment by ezntek** [comment]
your username "isn't valid", sorry

**Comment by Bloxxel64** [comment]
fu-

**Comment by ezntek** [comment]
add me, `ezntek`
