### ISSUE TITLE
Module not found error

### ISSUE THREAD

**Issue by OilFreak** [Bloxxel64/SM64LinuxLauncher-Legacy#8]
"Traceback (most recent call last):
  File "/home/MyName/SM64LinuxLauncher/./setup.py", line 5, in &lt;module&gt;
    from pip._internal import main as pip_main
ModuleNotFoundError: No module named 'pip'"
When trying to use setup.py

**Comment by ezntek** [comment]
right, the feature was deprecated.

I'll go submit a PR right now.

**Comment by ezntek** [comment]
try using my fork on this branch [here](https://github.com/ezntek/SM64LinuxLauncher/tree/fix-installer), i've fixed the bug.

Do let me know if it works. Cheers!

**Comment by OilFreak** [comment]
I regret to inform you that it does not.
Traceback (most recent call last):
  File "/home/MyName/SM64LinuxLauncher-fix-installer/./setup.py", line 5, in &lt;module&gt;
    from pip import main as pip_main
ModuleNotFoundError: No module named 'pip'

**Comment by ezntek** [comment]
i think you just dont have pip installed on your system.

try `python3 -m ensurepip`, where python3 can be any python interpreter

**Comment by OilFreak** [comment]
You should probably include a list of dependencies in the readme. It seems like I also need Tkinter

**Comment by OilFreak** [comment]
Also, the window is very small and squished. 4k issue?

**Comment by ezntek** [comment]
> You should probably include a list of dependencies in the readme. It seems like I also need Tkinter

I actually do not own the project, I only have a fork of it. You can go contact @Bloxxel64 or you can wait for me to finish my launcher.

As for pip, all standard python installs are supposed to include them, but linux installs don't. So you do need to install python3-tkinter and python3-pip (package names vary between distributions.)

> Also, the window is very small and squished. 4k issue?

i believe it is.

**Comment by ezntek** [comment]
@OilFreak do close this issue, please
